version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Hello
          command: |
            echo "hello-world"
      - run:
          name: Build
          command: |
            npm run build
