version: 2.1
orbs:
  node: circleci/node@5.1.0
  aws-cli: circleci/aws-cli@3.1.4
jobs:
  build_deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - aws-cli/setup
      - run:
          name: Build app
          command: |
            npm run build
      - run:
          name: Deploy app
          command: |
            npm run deploy

workflows:
  full_pipeline:
    jobs:
      - build_deploy:
          filters:
            branches:
              only: main
